spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.252.139:6033/libre?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: ENC(pS3X2GTc99Gw5vhMMZWmHzdvtRRHO1o3)
    type: com.zaxxer.hikari.HikariDataSource
  elasticsearch:
    uris: http://101.42.252.139:9200
    username: elastic
    password: ENC(hoWyhk+6Fzt7jqzr0DmeH3SP3Y/5hEMK)
    connection-timeout: 10s
video:
  download-path: /Users/libre/video/
  ffmpeg-path: /usr/local/Cellar/ffmpeg/5.0.1/bin/
  mp4box-path: /Applications/GPAC.app/Contents/MacOS/MP4Box/






jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: 504879189zc..
