server:
  port: 9870

spring:
  application:
    name: video-spider
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  codec:
    max-in-memory-size: 100MB

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      insert-strategy: not_null
      update-strategy: not_null
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: 504879189zc..

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://101.42.252.139:6033/libre?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: ENC(pS3X2GTc99Gw5vhMMZWmHzdvtRRHO1o3)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 1000000
      maximum-pool-size: 5
      max-lifetime: 1800000
      minimum-idle: 1

  elasticsearch:
    uris: http://101.42.252.139:9200
    username: elastic
    password: ENC(hoWyhk+6Fzt7jqzr0DmeH3SP3Y/5hEMK)
    connection-timeout: 10s

libre:
  oss:
    endpoint: http://101.42.252.139:9000
    access-key: libre
    secret-key: ENC(ETJLWDpbHdoI+lsUrh8QAlt7DUJvEVpz)

video:
  download-path: /Users/libre/video/
  ffmpeg-path: /usr/local/Cellar/ffmpeg/5.0.1/bin/
  mp4box-path: /Applications/GPAC.app/Contents/MacOS/MP4Box/

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.252.139:6033/libre?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: ENC(pS3X2GTc99Gw5vhMMZWmHzdvtRRHO1o3)
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 500
      min-idle: 50
      max-wait: 100000
      validation-query: select 1
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: ENC(pS3X2GTc99Gw5vhMMZWmHzdvtRRHO1o3)
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10

  elasticsearch:
    uris: http://172.17.0.3:9200
    username: elastic
    password: ENC(hoWyhk+6Fzt7jqzr0DmeH3SP3Y/5hEMK)

video:
  download-path: /libre/video/
  ffmpeg-path: /usr/bin/
  mp4box-path: /libre/gpac/gpac_public/bin/gcc/MP4Box/

libre:
  oss:
    endpoint: http://172.17.0.5:9000
    access-key: libre
    secret-key: ENC(ETJLWDpbHdoI+lsUrh8QAlt7DUJvEVpz)
