server:
  port: 9870

spring:
  application:
    name: Libre-Video
  profiles:
    active: dev

mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    name: "./logs/app.log"
