spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.252.139:6033/libre?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: ENC(pS3X2GTc99Gw5vhMMZWmHzdvtRRHO1o3)
    type: com.zaxxer.hikari.HikariDataSource
  elasticsearch:
    uris: http://101.42.252.139:9200
    username: elastic
    password: ENC(hoWyhk+6Fzt7jqzr0DmeH3SP3Y/5hEMK)

video:
  download-path: /root/video/
  ffmpeg-path: /usr/ffmpeg/bin/
  mp4box-path: /root/gpac/gpac_public/bin/gcc/MP4Box/


jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
