server:
  port: 9870

spring:
  application:
    name: Libre-Video
  profiles:
    active: prod

mybatis-plus:
  global-config:
    banner: false
    db-config:
      insert-strategy: not_empty
      update-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true

libre:
  xss:
    enabled: false

logging:
  file:
    name: "./logs/app.log"

